name: SwiftShader - Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-pragma-server:
    runs-on: windows-latest

    steps:
      - name: Install required packages
        shell: bash
        run: |
          git clone https://github.com/Silverlan/swiftshader.git
          cd swiftshader
          cd build
          cmake ..cmake --build . --parallel --config RelWithDebInfo
