name: SwiftShader - Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-pragma-server:
    runs-on: ubuntu-24.04

    steps:
      - name: Install required packages
        shell: bash
        run: |
          git clone https://github.com/Silverlan/swiftshader.git
          cd swiftshader
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Generate Release Archive
        shell: bash
        id: generate-archive
        run: |
          archiveName=binaries_linux64.tar.gz
          tar -czvf $archiveName swiftshader/build/bin/libvulkan.so.1
          mv $archiveName ../$archiveName
          echo "archive-name=$archiveName" >> $GITHUB_OUTPUT
          
      - name: Update Nightly Tag
        uses: rickstaa/action-create-tag@v1.3.9
        continue-on-error: true
        if: runner.os == 'Linux'
        with:
          tag: "latest"
          force_push_tag: true

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ steps.generate-archive.outputs.archive-name }}"
          body: "Automatically generated binaries."
          tag: latest
          replacesArtifacts: true
          allowUpdates: true
