name: Run Pragma Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-pragma-server:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download pragma-lin64.tar.gz
        run: wget https://github.com/Silverlan/pragma/releases/download/nightly/pragma-lin64.tar.gz -O pragma-lin64.tar.gz

      - name: Extract pragma-lin64.tar.gz
        run: tar -xzf pragma-lin64.tar.gz

      - name: Install required packages
        shell: bash
        run: |
          # Required to fix
          # /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install --only-upgrade libstdc++6

      - name: Run pragma_server
        run: |
          ./pragma_server -luaext -log 2 2 +map "test_physics" +"lua_exec tests/ci_runner_tests.lua"
          echo "Exit code: $?"
