name: Pragma CI2

on:
  repository_dispatch:
    types: [trigger-second-workflow]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Pragma
      run: |
        Invoke-WebRequest -Uri "https://github.com/Silverlan/pragma/releases/download/nightly/pragma-win64.zip" -OutFile "pragma-win64.zip"

    - name: Extract Pragma
      run: |
        Expand-Archive -Path "pragma-win64.zip" -DestinationPath "pragma"

    - name: Run Pragma Server
      run: |
        cd pragma
        .\pragma_server.exe -luaext -log 2 2 +map "test_physics" +"lua_exec tests/ci_runner_tests.lua"
      continue-on-error: true
      id: run-pragma

    - name: Print Exit Code
      run: echo Exit code was ${{ steps.run-pragma.outcome == 'success' && '0' || '1' }}
