name: Run Pragma Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-pragma-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download pragma-lin64.tar.gz
        run: wget https://github.com/Silverlan/pragma/releases/download/nightly/pragma-lin64.tar.gz -O pragma-lin64.tar.gz

      - name: Extract pragma-lin64.tar.gz
        run: tar -xzf pragma-lin64.tar.gz

      - name: Run pragma_server
        run: |
          ./pragma/pragma_server
          echo "Exit code: $?"
