name: Pragma CI2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install numpy
      shell: bash
      id: install-numpy
      run: |
        pip install numpy==1.26.4
